apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-nextjs
  namespace: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app-nextjs
  template:
    metadata:
      labels:
        app: todo-app-nextjs
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      # deployment.yaml initContainers block
      initContainers:
        - name: migrate
          image: ghcr.io/iamamanul/todo-app:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: NODE_OPTIONS
              value: "--openssl-legacy-provider"
          command: ["npx", "prisma", "migrate", "deploy"] 
      containers:
        - name: web
          image: ghcr.io/iamamanul/todo-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
